# Site settings
title: Tanvi Malhotra
email: tanviimalhotra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    “But he who dares not grasp the thorn
    Should never crave the rose.”
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tanvi-m.github.io" # the base hostname & protocol for your site
twitter_username: malhotra_tanvi
github_username:  tanvi-m

# Build settings
markdown: kramdown
gems:
  - jemoji
